version: '3'

services:
  # postgres db image from docker
  db:
    image: postgres
  # django web server
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - secrets/.env-local
    volumes:
      - .:/usr/src/poetster
    ports:
      - "8000:8000"
    depends_on:
      - db