# Generated by Django 2.2.8 on 2020-01-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0002_poem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
