# Generated by Django 2.2.8 on 2020-01-13 03:30

from django.db import migrations, models
import poem.models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0004_auto_20200109_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=poem.models.poem_image_file_path),
        ),
    ]
